sudo: required
services:
  - docker

before_install:
  - docker build -t edsonnaza/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edsonnaza/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeantalk-us-west-2-306476627547"
  buchet_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"